/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://df5lvso2ejbfdhsasof6ru55ku.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mdfhbshkv5eczinp2tseakgdfu",
    "aws_cognito_identity_pool_id": "us-west-2:dd04e438-02f2-4318-8199-12bfdbcff788",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VMlrfCucV",
    "aws_user_pools_web_client_id": "2ijo63gsbo1ac48e5ud21dtche",
    "oauth": {}
};


export default awsmobile;
